### ISSUE TITLE
Writing to Google Sheets

### ISSUE THREAD

**Issue by drvladb** [jovotech/jovo-framework#449]
## I'm submitting a...

- [ ] Bug report
- [x] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

It should work by being able to write to Google Sheets using jovo-cms-googlesheets and the Google Cloud API
### Error log
```
If you have an error log, please paste it here.
```

## Your Environment

* Jovo Framework version used: 2.1.5
* Operating System: Mac os 10.14 with NPM installed by HomeBrew

**Comment by jankoenig** [comment]
Hi @drvladb, do you have a specific use case for this?
Would it be to edit specific cells, or rather about adding new rows to a sheet?

Thanks,
Jan

**Comment by drvladb** [comment]
More like specific cells

**Comment by dumaalex998** [comment]
Hi! 
Is there any updates on this feature request? 
Since I'm using Google Sheets CMS to manage my data (it's a private file, so I have it configured in the _/credentials_ folder) it would be really awesome if we could also write to it.
In my specific example I use Google Sheets to read data and Airtable API to write data (I allow users to leave feedbacks and feature requests and I can see them live in the same base on Airtable).
Having it all together on Google Sheets would help me a lot, allowing me to get rid of an entire service in my architecture.
Let me know if I can help you build this!

**Comment by aswetlow** [comment]
Hey @dumaalex998 
There's no news in this regard. Thanks for your offer to help. 
We will discuss it internally and try to come up with more details.

**Comment by aswetlow** [comment]
I close this issue due to inactivity.
