### ISSUE TITLE
Unable to use 'jovo-platform-core' package

### ISSUE THREAD

**Issue by vinamrajais** [jovotech/jovo-framework#765]
## I'm submitting a...

- [ x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
I should be able to use 'jovo-platform-core' package.
```
const { CorePlatform } = require('jovo-platform-core');
const corePlatform = new CorePlatform();
app.use(corePlatform);
```

## Current Behavior
Using 'jovo-platform-core' is throwing error on launch of hello world app. There is no request headers shown in webhook.

### Error log
```
Error -----------------------------------------------------------------
 Message:
 Cannot read property 'audio' of undefined
 Stack:
 TypeError: Cannot read property 'audio' of undefined
   at CorePlatform.request (/Users/vinamra/Documents/CBM/ATOM/CODE/ALEXA/core-platform-web-hello-world/node_modules/jovo-platform-core/src/CorePlatform.ts:101:8)
   at Middleware.run (/Users/vinamra/Documents/CBM/ATOM/CODE/ALEXA/core-platform-web-hello-world/node_modules/jovo-core/src/core/Middleware.ts:85:20)
   at App.handle (/Users/vinamra/Documents/CBM/ATOM/CODE/ALEXA/core-platform-web-hello-world/node_modules/jovo-core/src/core/BaseApp.ts:220:41)
   at processTicksAndRejections (internal/process/task_queues.js:97:5)
   at App.handle (/Users/vinamra/Documents/CBM/ATOM/CODE/ALEXA/core-platform-web-hello-world/node_modules/jovo-framework/src/App.ts:333:5)
   at /Users/vinamra/Documents/CBM/ATOM/CODE/ALEXA/core-platform-web-hello-world/src/index.js:20:9
  ----------------------------------------------------------------------

```
## Your Environment
* Jovo CLI Version: 3.0.12

Jovo packages of current project:
  jovo-core: 3.0.16
  jovo-db-filedb: 3.0.17
  jovo-db-platformstorage: 3.0.16
  jovo-framework: 3.0.18
  jovo-platform-alexa: 3.0.20
  **jovo-platform-core: 3.0.18**
  jovo-platform-dialogflow: 3.0.16
  jovo-platform-googleassistant: 3.0.18
  jovo-plugin-debugger: 3.0.16
  jovo-slu-witai: 3.0.17

* Operating System: Mac

**Comment by fabrizzioalco** [comment]
Hey, i would take a look at this.

**Comment by fabrizzioalco** [comment]
Actually there's no jovo-platform-core as a package
i think you meant jovo-core

**Comment by fabrizzioalco** [comment]
@jankoenig Hey, this is actually right, isn't it? You can't use java-platform-core because that package has an internal use in jovo-core.

**Comment by m-ripper** [comment]
Hey, sorry for getting to you so late.

Based on the issue here jovotech/jovo-client-web-starters#4 I assume OP used the `jovo-debugger` to test the `jovo-platform-core`-integration. Is that the case for you as well?

I will make a note in the docs soon that the `jovo-debugger` currently does not support the `jovo-platform-core`-package, but this is something we're definitely looking forward to implement!

If you want to test your app I would recommend you to check out [this repository](https://github.com/jovotech/jovo-client-web-starters).

And to clear things up, `jovo-core` is the package that is used by every platform and app and the `jovo-platform-core` package is our custom platform which is supposed to be usable with multiple types of devices, i.e. mobile, web and more.

I hope this answers your question.

**Comment by vinamrajais** [comment]
Yes we started using jovo-client-web-starters project and not using jovo-debugger.
Same is being mentioned in slack channel.

Thanks for detailed information.
