### ISSUE TITLE
Dashbot failing to build

### ISSUE THREAD

**Issue by PrasadPotale** [jovotech/jovo-framework#783]
Followed the steps as per the analytics SDK for Dashbot integration, getting following error,  

node_modules/jovo-analytics-dashbot/dist/src/DashbotAlexa.d.ts:1:29 - error TS7016: Could not find a declaration file for module 'dashbot'

Any help, Thanks.

**Comment by m-ripper** [comment]
Hey there!

The problem is caused because the `dashbot`-package does not provide types. \
You have to two possible options to resolve this error:
1. (Recommended) Declare types for the package:
```
declare module 'dashbot';
```
in a `.d.ts`-file. For more information take a look [here](https://www.typescriptlang.org/docs/handbook/modules.html#working-with-other-javascript-libraries).
> This is just a quick fix. Theoretically, you could declare the actual types. 

2. Set `skipLibCheck` to `true` in the `tsconfig.json`

**Comment by PrasadPotale** [comment]
Thanks a lot @m-ripper worked for me.
